### ISSUE TITLE
use regular maven lifecycle instead of site?

### ISSUE THREAD

**Issue by hohwille** [oasp/oasp-docgen#18]
What was the rationale behind using the site lifecycle to build the documentation?
IMHO we should use the regular lifecycle so we can `mvn install` and especially for releases even `mvn deploy`. This way we could have all PDFs with proper release numbers in maven central.
WDYT?

**Comment by maybeec** [comment]
There was no rational behind it rather than the convention to provide documentation on the site life cycle. There is also site-deploy as an goal.
I am pretty non-emotional about this topic, but I don't see any reason as of the site-deploy goal to break with this convention.

**Comment by hohwille** [comment]
fixed in devon-docgen:
https://github.com/devonfw/devon-docgen/
use that instead.
