### ISSUE TITLE
Replace oasp-docgen with asciidoctor-maven-plugin

### ISSUE THREAD

**Issue by hohwille** [oasp/oasp-docgen#9]
oasp-docgen is entirely obsolete and can be completely replaced by asciidoctor-maven-plugin:
https://github.com/asciidoctor/asciidoctor-maven-plugin

We might want to create a parent pom to establish some common OASP standards here but actually we only need a small `pom.xml` that we add to our wikis and then can build the pdf using maven without any further external resources such as oasp-docgen.

**Comment by hohwille** [comment]
Malte prepared the parent POM for that:
https://github.com/oasp/oasp-docgen/blob/asciidoctor-parentpom/pom.xml

The only blocker left to go is to fiddle out a solution to get the custom footers/headers working.
Then we can replace the existing solution entirely with the new solution and deploy the parent POM to maven central (we can already do that meanwhile and update to a new version afterwards).

**Comment by maybeec** [comment]
1. I opened a feature request for this quite some time ago: asciidoctor/asciidoctor-pdf#849
This would make life easier. Currently, you can solve it by defining a theme with a hard coded header + footer or we have to write any additional preprocessing to get the footer somehow from the existing wiki footer definitions.
2. If we want to provide a common style for all devonfw documents, we cannot simply just deploy a pom.xml but also the style doc somewhere. Maybe in an additional jar deployment? Has to be tested.
2. In addition, there is a big pitfall of the custom styles so far. There is currently no notion of inheritance of style definitions. So if you want to adapt the style for your specific project, you have to redundantly specify all the common styles again... at least that was what I could find out, which leads me to the decision to not continue with styling :)
